name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.0'
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          cypress:open: npm run cypress:open
          