name: cypress test

on: [push]

jobs:
  php-test:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12
        
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        cypress:open: npm run cypress:open
