name: teste de actions

on: push

jobs:

  executa-a-action:
    runs-on: ubuntu-latest
    steps:
      - name: executa a actions
        uses: actions/hello-world-javascript-action@v1
        id: executa-action
        with:
          who-to-greet: rodrigo
      - name: print o resultado
        run: echo "${{ steps.executa-action.outputs.time }}"