name: teste

on: push

jobs:
    primeiro-job:
        runs-on: ubuntu-latest
        steps:
            - name: primeiro-passo
              run: echo ola
            - name: segundo passo
              run: |
                  node -v
                  npm -v
    segundo-job:
        runs-on: ubuntu-latest
        needs: ['primeiro-job']
        steps:
            - name: primeiro passo do segundo job
              run: ls
